### ISSUE TITLE
Backport fixes from EOS

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-FC#16]
* [x] https://github.com/EOSIO/eos/pull/3560
* [ ] openssl config path https://github.com/EOSIO/eos/commit/42baafc5015b87cdf439db1fa36421773c17a81e
* [ ] handle bad_alloc https://github.com/EOSIO/eos/pull/3564/files
* [ ] https://github.com/EOSIO/eos/pull/3392/files - **Careful, might break things!**
* [ ] reflector_verifier, exception strings https://github.com/EOSIO/eos/pull/3277
* [ ] gelf logging https://github.com/EOSIO/eos/commit/2d980b46a383f6cda346025cfbdc83185b7480ef
/ab87a832bec5cc0301d4efc1662de6ecd0e183ea
* [ ] http performance https://github.com/EOSIO/eos/pull/3240/files
* [ ] logger mutex https://github.com/EOSIO/eos/pull/3037/files
* [ ] check pubkey validity https://github.com/EOSIO/eos/commit/e0e812bcfab599d804e4ad5fcc1fbe259470160c
* [x] remove unused bzip2 dependency https://github.com/EOSIO/eos/commit/142ccba9b5e2f147a3c80eaf01aad549d84265ca
/4089d76394e7513f32326c562de80dfc8998ca27
* [ ] UDP fixes https://github.com/EOSIO/eos/commit/9224efeaa8e47a124996c8e8f849ecd1eb85b224 https://github.com/EOSIO/eos/pull/2458
* ~~minor cleanup https://github.com/EOSIO/eos/pull/3077/files~~ n/a
* ~~native 128bit support https://github.com/EOSIO/eos/commit~~ apparently unsupported by VC
* ~~backport FC_LOG_AND_DROP macro https://github.com/EOSIO/eos/commit~~ equivalent to FC_CAPTURE_AND_LOG
* ~~variant decoding https://github.com/EOSIO/eos/commit/25a1dd94e60c4aa813392f7733abcd306cb92ff3~~ this is a breaking change

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-FC#2
